# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP .NET Core service.

version: '3.4'

services:
  weather:
    image: weather
    build:
      context: .
      dockerfile: server/Weather/Dockerfile
    ports:
      - 5000:5000
  nginx:
      image: nginx:latest
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      depends_on:
        - weather
      ports:
        - "80:80"